﻿# docker-compose.yml
version: "3.3"
services:
#  seq:
#    image: datalust/seq:latest
#    ports:
#      - 5341:80
#    environment:
#      ACCEPT_EULA: Y
#    restart: unless-stopped
#    volumes:
#        - ./seq-data:/data
  ekipchi:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ekipchi
#    depends_on:
#      - seq
#    environment:
#      WAIT_HOSTS: seq:5341
#